---
- hosts: Jenkins
  become: yes
  
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Jenkins and SonarQube images
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - jenkins/jenkins:lts

    - name: Run Jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        published_ports:
          - "8080:8080"
          - "50000:50000"

    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 60

    - name: Get initial admin password
      command: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password
      until: jenkins_password.rc == 0
      retries: 5
      delay: 10

    - name: Print Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"

    - name: Install Groovy in Jenkins container
      command: docker exec --user root jenkins bash -c "apt-get update && apt-get install -y groovy"


    - name: Create init.groovy.d directory in Jenkins container
      command: docker exec --user root jenkins mkdir -p /var/jenkins_home/init.groovy.d

    - name: Copy basic setup Groovy script to Jenkins container
      command: docker cp /tmp/basic-setup.groovy jenkins:/var/jenkins_home/init.groovy.d/basic-setup.groovy



    - name: Restart Jenkins container to apply configuration
      docker_container:
        name: jenkins
        state: stopped

    - name: Start Jenkins container after applying Groovy script
      docker_container:
        name: jenkins
        state: started
    
    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 60

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present
      become: true

    - name: Install python-jenkins library
      command: /usr/bin/python3 -m pip install python-jenkins
      become: true

    - name: Create a jenkins job using basic authentication
      community.general.jenkins_job:
        config: "{{ lookup('file', 'pipeline-config.xml') }}"
        name: test
        password: admin
        url: http://3.84.190.98:8080
        user: admin

    
